### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by fschulze** [comlounge/embeddify#11]
From my side everything is ready for a 0.3.0 release. If you don't have time for it, I can upload it and make a PR which you can then tag.

**Comment by mrtopf** [comment]
Thanks for all the work. Please just go ahead and I maybe simply transfer this repo to you then, if that's ok with you (as I don't see myself working on it anytime soon on it anyway and you seem to know what you are doing).

**Comment by fschulze** [comment]
I'd be fine with that, or you add me to the repository, then existing links won't change. Whatever works better for you.

**Comment by mrtopf** [comment]
right, that also is an option. I added you now.

**Comment by fschulze** [comment]
I don't have permission to push.

**Comment by mrtopf** [comment]
push where? to pypi? or github? 
in pypi I see you as maintainer. Shouldn't this work?

**Comment by mrtopf** [comment]
I also made you owner on pypi now.

**Comment by fschulze** [comment]
I meant github, to update the changelog and make the tag.

**Comment by mrtopf** [comment]
I think you still need to accept the invite. I also sent you a mail with the link.

**Comment by fschulze** [comment]
Got it, works now.
