### ISSUE TITLE
Additional infos

### ISSUE THREAD

**Issue by fschulze** [comlounge/embeddify#8]
I'd like to be able to access additional infos, like the optional ``thumbnail_url``. I think the easiest way without changing the current API, would be an object inheriting from ``str`` which has ``data`` as an additional attribute containing the raw JSON data as a parsed ``dict`` which is already available in ``OEmbedPlugin.__call__``.
What do you think about that?

**Comment by mrtopf** [comment]
As I am not really into the project right now I will leave the decision to you. I will happily merge a PR then.
